
name: Tests
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - swift:5.7
    container:
      image: ${{ matrix.tag }}
    
    steps:
    - uses: actions/checkout@v3
    - run: swift test

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: swift test
